[{
  make: "Toyota",
  model: "Corolla",
  year: 2020,
  color: "White",
  price: 23500,
  img: "https://via.placeholder.com/300",
  type: "Sedan",
  description: "A compact car with excellent fuel efficiency.",
},
{
  make: "Honda",
  model: "Civic",
  year: 2021,
  color: "Black",
  price: 24900,
  img: "https://via.placeholder.com/300",
  type: "Sedan",
  description: "A sporty car with a sleek design.",
},
{
  make: "Ford",
  model: "F-150",
  year: 2022,
  color: "Red",
  price: 42500,
  img: "https://via.placeholder.com/300",
  type: "Truck",
  description: "A powerful truck for work and play.",
},
{
  make: "Chevrolet",
  model: "Equinox",
  year: 2019,
  color: "Blue",
  price: 31200,
  img: "https://via.placeholder.com/300",
  type: "SUV",
  description: "A versatile SUV with plenty of cargo space.",
},
{
  make: "BMW",
  model: "3 Series",
  year: 2022,
  color: "Silver",
  price: 54000,
  img: "https://via.placeholder.com/300",
  type: "Sedan",
  description: "A luxury car with advanced technology features.",
},
{
  make: "Toyota",
  model: "Sienna",
  year: 2021,
  color: "Gray",
  price: 39400,
  img: "https://via.placeholder.com/300",
  type: "Van",
  description: "A spacious van for family and cargo.",
},
{
  make: "Jeep",
  model: "Wrangler",
  year: 2020,
  color: "Green",
  price: 39200,
  img: "https://via.placeholder.com/300",
  type: "SUV",
  description: "An iconic SUV with off-road capabilities.",
},
{
  make: "Hyundai",
  model: "Kona",
  year: 2022,
  color: "Orange",
  price: 27900,
  img: "https://via.placeholder.com/300",
  type: "SUV",
  description: "A compact SUV with a fun and quirky design.",
},
{
  make: "Tesla",
  model: "Model 3",
  year: 2022,
  color: "Black",
  price: 65400,
  img: "https://via.placeholder.com/300",
  type: "Electric",
  description: "A sleek electric car with autopilot features.",
},
{
  make: "Audi",
  model: "A4",
  year: 2021,
  color: "White",
  price: 57800,
  img: "https://via.placeholder.com/300",
  type: "Sedan",
  description: "A sophisticated car with a refined interior.",
}]


